# Enable GPIO driver
CONFIG_GPIO=y

# Enable Console & UART Output
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y

# Enable Logging
CONFIG_LOG=y
CONFIG_STEPPER_LOG_LEVEL_INF=y

# Enable SPI & Stepper Drivers
CONFIG_SPI=y
CONFIG_STEPPER=y
CONFIG_STEPPER_ADI_TMC51XX=y
CONFIG_STEPPER_ADI_TMC51XX_STEPPER_CTRL=y
CONFIG_STEPPER_ADI_TMC51XX_STEPPER_DRIVER=y
CONFIG_STEPPER_ADI_TMC51XX_RAMP_GEN=y
CONFIG_STEPPER_ADI_TMC51XX_RAMPSTAT_POLL_INTERVAL_IN_MSEC=50

